---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0  # Use the ref you want to point at
    hooks:
      # Makes sure files end in a newline and only a newline.
      # See also: mixed-line-ending
      - id: end-of-file-fixer

      # Trims trailing whitespace.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      #  Prevent giant files from being committed.
      #  Specify what is "too large" with args: ['--maxkb=123'] (default=500kB)
      - id: check-added-large-files

      # Checks that non-binary executables have a proper shebang.
      - id: check-executables-have-shebangs

      # Checks for symlinks which do not point to anything.
      - id: check-symlinks

      # git {{{
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # git }}}

      # Secrets {{{
      # Check for the existence of private keys.
      - id: detect-private-key

      # Checks for the existence of AWS secrets that you have set up with the
      # AWS CLI. The following arguments are available:
      #    --credentials-file - additional AWS CLI style configuration file in a
      #    non-standard location to fetch configured credentials from. Can be
      #    repeated multiple times.
      - id: detect-aws-credentials
      # Secrets }}}

      # Python {{{
      # Run flake8 on your python files.
      - id: flake8

      # Add # -*- coding: utf-8 -*- to the top of python files.
      - id: fix-encoding-pragma
      # Python }}}

  # shellcheck {{{
  - repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.4
    hooks:
      - id: shell-lint
  # shellcheck }}}


# vim: ft=yaml foldmethod=marker
