# https://starship.rs/config/

[character]
symbol = "$"
add_newline = true
style_success = "white"
style_failure = "red"

[username]
disabled = false
show_always = true
style_user = "fg:38 bold"
style_root = "bg:red fg:black"

[cmd_duration]
prefix = "⏲️"
min_time = 2000
style = "fg:15 dimmed"

[env_var]
style = "fg:0 bg:15"
variable = "PYTHONWARNINGS"
prefix = "PYTHONWARNINGS="

[aws]
disabled = true

[terraform]
disabled = false

[python]
python_binary = "python3"

[git_branch]
style = "green"

[git_status]
# prefix = ""
# suffix = ""
ahead = "👆🏻"
behind = "👇🏻"
# conflicted = "💥"
conflicted = "⚔️"
# modified = "🛠️"
modified = "✏️"
stashed = "📦"
renamed = "🌈"
untracked = "❔"
deleted = "❌"
diverged = "🔀"
staged = "🎭"
style = "green"
