# https://starship.rs/config/

add_newline = false

prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "docker_context",
    "package",
    "golang",
    "python",
    "ruby",
    "rust",
    "terraform",
    "nix_shell",
    "memory_usage",
    "aws",
    "env_var",
    "cmd_duration",
    "jobs",
    "custom",
    "line_break",
    "battery",
    "time",
    "character",
]


[character]
symbol = "$"
style_success = "white"
style_failure = "red"

[username]
disabled = false
show_always = true
style_user = "fg:38 bold"
style_root = "bg:red fg:black"

[cmd_duration]
prefix = "⏲️"
min_time = 2000
style = "fg:15 dimmed"

[env_var]
style = "fg:0 bg:15"
variable = "PYTHONWARNINGS"
prefix = "PYTHONWARNINGS="

[aws]
disabled = true

[terraform]
disabled = false

[python]
python_binary = "python3"

[git_branch]
style = "green"

[git_status]
# prefix = ""
# suffix = ""
ahead = "↑"
behind = "↓"
conflicted = "C"
modified = "M"
renamed = "R"
untracked = "U"
deleted = "X"
diverged = "D"
staged = "S"
style = "yellow"
